import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '../../components/Navbar'
import Footer from '../../components/Footer'
import CartState from '../../components/CartState'
import Loadingbar from '../../components/Loadingbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'codeswear.com - Wear the Code',
  description: 'codeswear.com - Generated by create next app',
}

export default function RootLayout({ children }) {

  return (
    // <html lang="en" className='overflow-x-hidden'>
    //   <body className={inter.className}>
    <>
      <Loadingbar />
      <CartState>
        <Navbar />
        {children}
        <Footer />
      </CartState>
    </>
    //   </body>
    // </html>
  )
}
